baseURL = 'https://browsergate.eu/'
title = 'BrowserGate'

contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
ignoreFiles = ['\.obsidian']
enableGitInfo = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[permalinks]
  blog = '/:section/:year/:month/:day/:slug'

[imaging]
  resampleFilter = 'CatmullRom'
  quality = 75
  anchor = 'smart'

[languages]
  [languages.en]
    languageName = 'English'
    title = 'BrowserGate'
    [languages.en.params]
      description = 'LinkedIn: uncovered. unhinged. uncontrolled. unauthorized.'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'tango'
    noClasses = false

[outputs]
  home = ['HTML', 'print', 'RSS']
  section = ['HTML', 'print', 'RSS']

[params]

  offlineSearch = true

  [params.copyright]
    authors = 'BrowserGate'
    from_year = 2025

  [params.ui]
    breadcrumb_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    sidebar_menu_foldable = true
    sidebar_menu_compact = false
    sidebar_search_disable = false
    showLightDarkModeMenu = false

    [params.ui.feedback]
      enable = false

    [params.ui.readingtime]
      enable = false

  [params.links]

[module]
  [module.hugoVersion]
    extended = true
    min = '0.155.0'
  [[module.imports]]
    path = 'github.com/google/docsy'
    disable = false
